# Issue types
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: question
  color: "d876e3"
  description: Further information is requested

# Priority
- name: priority/high
  color: "b60205"
  description: High priority

- name: priority/low
  color: "c5def5"
  description: Low priority

# Status
- name: triage
  color: "fbca04"
  description: Needs triage

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

- name: duplicate
  color: "cfd3d7"
  description: This issue or pull request already exists

# Maintenance
- name: chore
  color: "fef2c0"
  description: Maintenance tasks

- name: dependencies
  color: "0366d6"
  description: Dependency updates

# Release
- name: breaking
  color: "b60205"
  description: Breaking change

- name: skip-changelog
  color: "e4e669"
  description: Exclude from changelog
